import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DynamicalSystemsRelationsProbabilityTheoryTheoremCanonicalLaneLean.DynamicalSystems
import HautevilleHouse.DynamicalSystemsRelationsProbabilityTheoryTheoremCanonicalLaneLean.ProbabilityTheory

namespace HautevilleHouse
namespace DynamicalSystemsRelationsProbabilityTheoryTheoremCanonicalLaneLean

def ConstrainedDynamicalSystemsProbabilityClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_dynamical_systems_probability_endgame (A : AdmissibleClass) :
    ConstrainedDynamicalSystemsProbabilityClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DynamicalSystemsRelationsProbabilityTheoryTheoremCanonicalLaneLean
end HautevilleHouse